version: 2

# Run configuration
run:
  timeout: 1m
  tests: true

# Enable both the default linters and additional ones
linters:
  disable-all: true
  enable:
    # Default linters that were already enabled
    - errcheck    # Checks for unchecked errors
    - govet       # Examines Go source code for suspicious constructs
    - ineffassign # Detects when assignments to existing variables are not used
    - staticcheck # Set of rules from staticcheck
    - unused      # Checks for unused constants, variables, functions and types
    
    # Additional linters we want to enable
    - gocyclo     # Checks cyclomatic complexity

# Formatting options
issues:
  exclude-use-default: false